#spring.security
spring:
  security:
    user:
      name: wcc
      password: wcc123
  datasource:
    username: root
    password: bdp123
    url: jdbc:mysql://10.45.46.116:3306/ksrm
# eureka
eureka:
  instance:
    hostname: localhost
    port: 9000
    prefer-ip-address: true
    #心跳间隔5s，默认30s。每一个服务配置后，心跳间隔和心跳超时时间会被保存在server端，不同服务的心跳频率可能不同，server端会根据保存的配置来分别探活
    lease-renewal-interval-in-seconds: 5
    #心跳超时时间10s，默认90s。从client端最后一次发出心跳后，达到这个时间没有再次发出心跳，表示服务不可用，将它的实例从注册中心移除
    lease-expiration-duration-in-seconds: 10
  client:
    # 服务地址
    service-url:
      # 不可以写为default-zone
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.instance.port}/eureka